# Generated by Django 2.1.7 on 2019-11-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=64)),
                ('visitor_email', models.CharField(max_length=64)),
                ('visitor_phone', models.IntegerField()),
                ('host_name', models.CharField(max_length=64)),
                ('host_email', models.CharField(max_length=64)),
                ('host_phone', models.IntegerField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
            ],
        ),
    ]
