# Generated by Django 2.1.7 on 2019-11-30 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitinfo',
            old_name='check_in',
            new_name='checkin_date_time',
        ),
        migrations.RenameField(
            model_name='visitinfo',
            old_name='check_out',
            new_name='checkout_date_time',
        ),
    ]
